helhist_search.settings:
  type: config_object
  label: 'HelHist search settings'
  mapping:
    search_page_node:
      type: string
      label: 'Search page node'
    mapping_mode:
      type: string
      label: 'Search mapping mode'
