mode: simple
ignored_config_entities:
  - 'easy_breadcrumb.settings:home_segment_title'
  - 'hdbt_admin_tools.site_settings:site_settings'
  - 'helhist_kore_admin.settings'
  - 'helhist_search.settings'
  - 'system.site:page.front'
  - 'webform.webform.*'
