_core:
  default_config_hash: 68A3PDsSIoX2q7iFOa2lMdnYkgKgem4uh1_RBxcRVWU
report-only:
  enable: false
  directives: {  }
  reporting:
    plugin: none
enforce:
  enable: true
  directives:
    default-src:
      base: self
    img-src:
      base: self
      sources:
        - 'https://server.arcgisonline.com'
        - 'https://kartta.hel.fi'
        - 'https://a.tile.openstreetmap.org'
        - 'https://b.tile.openstreetmap.org'
        - 'https://c.tile.openstreetmap.org'
    script-src:
      base: self
      flags:
        - report-sample
        - unsafe-inline
        - wasm-unsafe-eval
      sources:
        - 'https://e.infogram.com'
        - 'https://webanalytics.digiaiiris.com'
    style-src:
      base: self
      flags:
        - report-sample
        - unsafe-inline
    base-uri:
      base: none
    frame-ancestors:
      base: self
    frame-src:
      base: self
      sources:
        - 'https://e.infogram.com'
    connect-src:
      base: self
      sources:
        - 'https://api.finna.fi'
  reporting:
    plugin: none
