on:
  pull_request:
  push:
    branches: ['main', 'dev']
name: CI
jobs:
  tests:
    uses: kirkkala/hel-drupal-gh-actions/.github/workflows/project-tests.yml@feature/check_config_language-ignore_files
    secrets:
      sonarcloud_token: ${{ secrets.SONAR_TOKEN }}
    with:
      check_config_language: true
      check_config_language_ignore_files: "webform.webform.*,views.view.*"
