on:
  pull_request:
  push:
    branches: ['main', 'dev']
name: CI
jobs:
  tests:
    uses: city-of-helsinki/drupal-gh-actions/.github/workflows/project-tests.yml@main
    secrets:
      sonarcloud_token: ${{ secrets.SONAR_TOKEN }}
    with:
      check_config_language: true
      check_config_language_ignore_files: "webform.webform.*,webform.settings"
